/**
 * DanceGesture.cpp — 87-keyframe West Coast Swing dance
 *
 * A looping sequence of smooth, rhythmic joint-space moves composed
 * algorithmically from a position library harvested across all gestures.
 *
 * West Coast Swing rhythm patterns:
 *   - Anchor steps (grounding settle near home)
 *   - Triple steps (quick-quick-slow flowing arcs)
 *   - Sugar pushes (push out + catch + pull back)
 *   - Side passes (lateral sweeps)
 *   - Whips (circular sweeps with direction changes)
 *   - Sways (gentle side-to-side)
 *   - Body rolls (shoulder-then-elbow waves)
 *
 * Song structure: intro → verse → bridge → verse → outro
 * with alternating side bias and tempo humanization (±8%).
 *
 * Grip choreography: multi-frequency sinusoidal phase offsets,
 * percussive snaps on catches, flowing opens on reaches.
 *
 * Generated by generate_dance.py from the position library.
 *
 * Joint limits: base ±90°, shoulder -109..+104°, elbow ±100°, grip ±90°
 */

#include "DanceGesture.h"

// Joint-space keyframe: {base, shoulder, elbow, grip, durationMs}
struct DanceKey {
    float    base;
    float    shoulder;
    float    elbow;
    float    grip;
    uint16_t durationMs;
};

// 87 keyframes — West Coast Swing dance loop
// Grip choreography: -30° = fully open, 45° = fully closed, 0° = neutral
static const DanceKey DANCE_KEYS[] PROGMEM = {
    {    0.0f,    0.0f,    0.0f,   45.0f, 1000 },  //  0: home (start)
    {    5.5f,    3.9f,   -2.4f,    0.0f,  468 },  //  1: anchor settle
    {    7.0f,    5.9f,    2.8f,    3.7f,  262 },  //  2: anchor side
    {    6.5f,    3.0f,   -4.5f,   31.5f,  248 },  //  3: anchor close
    {   -9.1f,    0.0f,    4.9f,    4.2f,  473 },  //  4: sway left
    {   -5.3f,   -9.6f,    8.7f,    5.0f,  524 },  //  5: sway left-back
    {   -5.3f,    2.6f,    8.7f,    4.7f,  533 },  //  6: sway center
    {    2.2f,    3.0f,    4.5f,   37.3f,  472 },  //  7: sway home
    {    8.2f,  -15.0f,   30.3f,  -21.1f,  374 },  //  8: triple side-open
    {    5.4f,   -6.9f,   35.3f,    6.9f,  404 },  //  9: triple arc
    {   -6.6f,   11.0f,   22.0f,   40.4f,  694 },  // 10: triple close
    {    2.8f,  -13.8f,   38.5f,  -13.9f,  525 },  // 11: sugar push out
    {   63.8f,  -76.5f,   54.0f,  -13.9f,  487 },  // 12: sugar extend
    {   16.5f,   -5.5f,   38.5f,   45.0f,  516 },  // 13: sugar catch
    {    0.0f,    0.0f,    8.8f,   39.3f,  513 },  // 14: sugar pull back
    {   -5.2f,    0.0f,    6.3f,   -8.3f,  532 },  // 15: sugar settle
    {    3.1f,   -3.5f,   -3.1f,   39.3f,  482 },  // 16: sugar anchor
    {    5.2f,   -3.5f,    3.1f,   -3.8f,  490 },  // 17: anchor settle
    {    4.4f,    4.2f,    0.0f,   11.5f,  259 },  // 18: anchor side
    {    0.0f,    0.0f,    8.8f,   34.5f,  245 },  // 19: anchor close
    {   -7.7f,   -9.9f,   44.0f,  -19.3f,  528 },  // 20: side pass out
    {  -60.0f,  -75.0f,   67.5f,   14.5f,  785 },  // 21: side sweep
    {  -19.9f,  -30.3f,   43.1f,   -1.7f,  809 },  // 22: side arc
    {   -5.3f,   -9.6f,    8.7f,   28.3f,  479 },  // 23: side settle
    {    3.3f,    3.9f,    2.4f,   28.3f,  532 },  // 24: side anchor
    {   14.3f,  -11.0f,   36.3f,  -24.0f,  497 },  // 25: body roll out
    {    0.0f,    5.5f,   22.0f,    9.1f,  350 },  // 26: body roll arc
    {    9.7f,   -1.0f,   31.7f,    2.6f,  363 },  // 27: body roll arc
    {    2.5f,    7.8f,    4.8f,   23.7f,  754 },  // 28: body roll home
    {  -22.0f,    5.5f,  -11.0f,  -19.9f,  349 },  // 29: triple side-open
    {    3.9f,   -8.2f,   30.2f,    5.4f,  350 },  // 30: triple arc
    {   -2.8f,   11.0f,   24.8f,   22.7f,  780 },  // 31: triple close
    {    0.0f,    0.0f,    8.8f,    4.9f,  527 },  // 32: anchor settle
    {    5.5f,    3.9f,   -2.4f,    9.9f,  247 },  // 33: anchor side
    {   -3.1f,    3.5f,    3.1f,   25.8f,  256 },  // 34: anchor close
    {    0.0f,  -11.0f,   38.5f,  -13.4f,  465 },  // 35: whip setup
    {    0.0f,  -78.8f,   -3.8f,  -13.4f,  496 },  // 36: whip sweep out
    {    0.0f,  -78.8f,   74.2f,   10.2f,  519 },  // 37: whip arc top
    {  -63.8f,  -76.5f,   54.0f,   45.0f,  470 },  // 38: whip direction!
    {    0.0f,    0.0f,   44.0f,   -2.5f,  487 },  // 39: whip swing back
    {   -2.8f,   16.5f,   16.5f,  -10.7f,  503 },  // 40: whip continue
    {   -7.0f,    5.9f,    2.8f,   31.7f,  464 },  // 41: whip decelerate
    {    0.0f,    0.0f,    6.3f,   31.7f,  498 },  // 42: whip anchor
    {   14.3f,    0.0f,   36.3f,  -20.5f,  386 },  // 43: triple side-open
    {   15.8f,   -2.8f,   26.2f,   14.3f,  358 },  // 44: triple arc
    {   -2.8f,   11.0f,   24.8f,   37.4f,  733 },  // 45: triple close
    {  -33.0f,    0.0f,   37.4f,  -23.9f,  530 },  // 46: sugar push out
    {  -63.8f,  -78.8f,   74.2f,  -23.9f,  481 },  // 47: sugar extend
    {   -9.9f,   -8.2f,   41.2f,   45.0f,  530 },  // 48: sugar catch
    {    0.0f,    0.0f,    8.8f,   40.4f,  484 },  // 49: sugar pull back
    {   -9.1f,   -7.0f,    4.9f,   -3.8f,  500 },  // 50: sugar settle
    {    1.1f,    1.6f,    5.8f,   40.4f,  471 },  // 51: sugar anchor
    {    4.1f,    7.8f,   -4.8f,   -2.7f,  522 },  // 52: sway right
    {    2.5f,    7.8f,    4.8f,   10.5f,  480 },  // 53: sway right-fwd
    {    4.4f,    4.2f,    0.0f,    1.8f,  520 },  // 54: sway center
    {    2.2f,    3.0f,    4.5f,   39.2f,  523 },  // 55: sway home
    {   -8.2f,   -5.5f,   38.5f,  -12.4f,  529 },  // 56: side pass out
    {  -60.0f,  -75.0f,   67.5f,    8.6f,  804 },  // 57: side sweep
    {    3.9f,   -8.2f,   30.2f,    4.9f,  704 },  // 58: side arc
    {   -5.3f,    2.6f,    8.7f,   34.4f,  496 },  // 59: side settle
    {    3.3f,    3.9f,    2.4f,   34.4f,  500 },  // 60: side anchor
    {    0.0f,   -5.5f,   38.5f,  -14.4f,  529 },  // 61: body roll out
    {   24.4f,   -2.5f,    9.1f,    5.3f,  400 },  // 62: body roll arc
    {   16.5f,   -5.5f,   38.5f,    8.8f,  357 },  // 63: body roll arc
    {    0.0f,    0.0f,    8.8f,   28.2f,  803 },  // 64: body roll home
    {   -5.2f,    0.0f,    6.3f,    3.3f,  500 },  // 65: anchor settle
    {   -5.3f,   -9.6f,    8.7f,   12.8f,  241 },  // 66: anchor side
    {    0.0f,    0.0f,    6.3f,   23.6f,  254 },  // 67: anchor close
    {   14.3f,  -11.0f,   36.3f,  -23.6f,  461 },  // 68: whip setup
    {  -28.5f,  -50.4f,   52.1f,  -23.6f,  492 },  // 69: whip sweep out
    {  -60.0f,  -75.0f,   67.5f,   13.5f,  516 },  // 70: whip arc top
    {   60.0f,  -75.0f,   67.5f,   45.0f,  667 },  // 71: whip direction!
    {    8.2f,  -15.0f,   30.3f,   -4.7f,  470 },  // 72: whip swing back
    {    0.0f,   11.0f,   19.2f,   -7.6f,  519 },  // 73: whip continue
    {    3.3f,    3.9f,    2.4f,   22.7f,  493 },  // 74: whip decelerate
    {    6.5f,    3.0f,   -4.5f,   22.7f,  492 },  // 75: whip anchor
    {   -6.6f,   11.0f,   22.0f,  -17.3f,  352 },  // 76: triple side-open
    {    0.8f,    6.0f,   20.8f,   14.9f,  380 },  // 77: triple arc
    {    0.0f,   22.0f,    8.2f,   25.9f,  745 },  // 78: triple close
    {    4.1f,    7.8f,   -4.8f,   -3.8f,  517 },  // 79: sway right
    {    5.6f,    3.2f,  -11.6f,   11.8f,  482 },  // 80: sway right
    {    4.4f,    4.2f,    0.0f,    0.5f,  464 },  // 81: sway center
    {    5.2f,   -3.5f,    3.1f,   31.8f,  514 },  // 82: sway home
    {    1.0f,    0.0f,   -6.3f,    0.7f,  503 },  // 83: anchor settle
    {   -3.1f,    3.5f,    3.1f,    3.8f,  243 },  // 84: anchor side
    {    0.0f,    0.0f,    6.3f,   37.5f,  241 },  // 85: anchor close
    {    0.0f,    0.0f,    0.0f,   45.0f, 1000 },  // 86: home (loop reset)
};
static const int DANCE_KEY_COUNT = sizeof(DANCE_KEYS) / sizeof(DANCE_KEYS[0]);

DanceGesture::DanceGesture(ArmController& ctrl, SmoothMover& smooth)
    : _ctrl(ctrl), _smooth(smooth),
      _running(false), _timeScale(1.0f), _phase(0) {
}

void DanceGesture::start() {
    _running = true;
    _phase = 0;
    _smooth.stopAll();
    _enqueueNextKeyframe();
    Serial.println("[Gesture] Dance started");
}

void DanceGesture::stop() {
    _running = false;
    _smooth.stopAll();
    // Smooth return to home (1s) instead of instant snap
    _smooth.startTimedMove(HOME_BASE, HOME_SHOULDER, HOME_ELBOW, HOME_GRIP, 1000);
    Serial.println("[Gesture] Dance stopped");
}

void DanceGesture::update() {
    if (!_running) return;

    // When the SmoothMover finishes the current keyframe, advance
    if (!_smooth.isBusy()) {
        _enqueueNextKeyframe();
    }
}

bool DanceGesture::isRunning() {
    return _running;
}

void DanceGesture::setSpeed(float speed) {
    // Convert speed (mm/s conceptually) to a time-scale:
    //   speed=80 → scale=1.0 (default)
    //   speed=160 → scale=2.0 (twice as fast)
    //   speed=40 → scale=0.5 (half speed)
    if (speed > 0.0f) {
        _timeScale = speed / 80.0f;
    }
}

void DanceGesture::_enqueueNextKeyframe() {
    const DanceKey& k = DANCE_KEYS[_phase % DANCE_KEY_COUNT];

    // Scale duration by time factor (faster timeScale = shorter duration)
    uint32_t duration = (uint32_t)(k.durationMs / _timeScale);
    if (duration < 50) duration = 50;  // Minimum duration guard

    _smooth.startTimedMove(k.base, k.shoulder, k.elbow, k.grip, duration);
    _phase++;
}
